name: Deploy Django REST Project to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_BASTION_SSH_PRIVATE_KEY }}
      EC2_URL: ${{ secrets.EC2_BASTION_URL }}
      EC2_USERNAME: ${{ secrets.EC2_BASTION_USERNAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: SSH to Private Server via Bastion
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add <(echo "$EC2_PRIVATE_SSH_PRIVATE_KEY")
          ssh -A -o StrictHostKeyChecking=no -i /dev/stdin $EC2_PRIVATE_USERNAME@$EC2_PRIVATE_URL
