name: Deploy Django REST Project to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_BASTION_SSH_PRIVATE_KEY }}
      EC2_URL: ${{ secrets.EC2_BASTION_URL }}
      EC2_USERNAME: ${{ secrets.EC2_BASTION_USERNAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_BASTION_URL }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.EC2_BASTION_URL }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: SSH to Private Server via Bastion
        run: |
          ssh -A -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_rsa \
              -J bastion-user@bastion-server-ip \
              private-user@private-server-ip << 'EOF'
              # Commands to run on the private server
              echo "Connected to private server via bastion"
